server:
  port: 5051
db:
  name: zfxc45jl4urbkf0o
spring:
  # h2:
  #   console:
  #     enabled: true
  datasource:
    url: jdbc:mysql://wmoxr8visxetqjem:yjbo3lg82pteyxhl@g4yltwdo6z0izlm6.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/zfxc45jl4urbkf0o
    username: wmoxr8visxetqjem
    password: yjbo3lg82pteyxhl
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'

