server:
  port: 5053
# db:
#   name: salesorderdb
# mongo:
#   database: heroku_1lvs8vf3
#   host: ds137687.mlab.com
#   port: 37687
spring:
  data:
    mongodb:
      uri: mongodb://heroku_bn01j0s7:labliblub123@ds149069.mlab.com:49069/heroku_bn01j0s7 

# spring:
#   data:
#     mongodb:
#       authentication-database: admin
#       username: heroku_1lvs8vf3
#       password: labliblub123
#       database: heroku_1lvs8vf3
#       port: 37687
#       host: ds137687.mlab.com

spring:
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  mail:
    host: localhost
    port: 25
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     
ui:
  serverUrl: http://localhost:4200/ 
management:
  endpoints:
    web:
      exposure:
        include: '*'